appName: myhelmapp

namespace: default

configmap:
  name: helpmapconfigmapv1.1
  data:
    CUSTOM_HEADER: :"This app was deployed with helm!"

image:
  name: devopsjourney1/mywebapp
  tag: latest